= Django Fixtures

A quick way to get data into/out of the Django DB

== Scenario

[.shrink]
Imagine we have a mesh network where each node reports the contacts it makes.
Our data comes from a CSV file: 

.meshmap/contacts.csv
[source, csv]
----
Timestamp,Source Name,Source Latitude,Source Longitude,Contact Name,Contact Latitude,Contact Longitude
2013-03-16T17:41:28+00:00,Base,40.71337075713575,-74.03556323098444,Park,40.71190693317326,-74.03737640423039 <1>
2013-03-16T17:41:29+00:00,Park,40.71190693317326,-74.03737640423039,Base,40.71337075713575,-74.03556323098444
2013-03-16T17:41:30+00:00,Pier,40.7134114184531,-74.03205490168605,Base,40.71337075713575,-74.03556323098444
2013-03-16T17:41:31+00:00,Base,40.71337075713575,-74.03556323098444,Pier,40.7134114184531,-74.03205490168605
2013-03-16T17:41:32+00:00,Pier,40.7134114184531,-74.03205490168605,Park,40.71190693317326,-74.03737640423039
2013-03-16T17:41:33+00:00,Park,40.71190693317326,-74.03737640423039,Pier,40.7134114184531,-74.0320549016860
----
<1> Note the formating of the timezone-aware timestamps.

== Creating a model

[.shrink]
Working from the data backwards, our first step would be to create a model:

.meshmap/main/models.py
[source, python]
----
from django.db import models

class Contact(models.Model):
    time = models.DateTimeField()
    source_name = models.CharField(max_length=30)
    source_lat = models.DecimalField(max_digits=9, decimal_places=6) <1>
    source_lon = models.DecimalField(max_digits=9, decimal_places=6)
    contact_name = models.CharField(max_length=30)
    contact_lat = models.DecimalField(max_digits=9, decimal_places=6)
    contact_lon = models.DecimalField(max_digits=9, decimal_places=6)
----
<1> Using a decimal for longitude and latitude will have consequences, but is
    probably a good idea.

== loaddata

[.shrink]
The `manage.py loaddata` command can import data from JSON (and YAML) files that
look like the following:

[source, json]
----
[
    {
        "model": "myapp.person",
        "pk": 1,
        "fields": {
            "first_name": "John",
            "last_name": "Lennon"
        }
    },
    {
        "model": "myapp.person",
        "pk": 2,
        "fields": {
            "first_name": "Paul",
            "last_name": "McCartney"
        }
    }
]
----

== Creating JSON fixture data

[.shrink]
We can use a python script to make our fixture. Python has great support for
CSV and JSON formats:

.meshmap/make_fixture.py
[source, python]
----
"""
Basic script for reading a CSV listing of contacts from `contacts.csv` and
creating a Django fixture in `contacts.json`. Fixtures can be loaded into
the DB with the `manage.py loaddata` command.
"""
import csv
import json

with open('contacts.csv', newline='') as csvfile:
    pk = 1
    contacts = []
    next(csvfile) # skip the header row
    for row in csv.reader(csvfile):
        contact = {
            'model': 'main.contact',
            'pk': pk,
            'fields': {
                'time': row[0],
                'source_name': row[1],
                # NOTE: this decimal to float conversion will lose precision, a
                # better solution would be a custom serializer and the Decimal
                # type: https://stackoverflow.com/questions/1960516/python-json-serialize-a-decimal-object
                'source_lat': float(row[2]),
                'source_lon': float(row[3]),
                'contact_name': row[4],
                'contact_lat': float(row[5]),
                'contact_lon': float(row[6]),
            }
        }
        contacts.append(contact)
        pk += 1
    with open('contacts.json', 'w') as jsonfile:
        jsonfile.write(json.dumps(contacts, sort_keys=True, indent=4))
----

== Running make_fixture.py and importing the data

[.shrink]
Now all we have to do is run our script and import the fixture:

[source, console]
----
PS C:\Users\rxt1077\IS601\meshmap> py -3 make_fixture.py
PS C:\Users\rxt1077\IS601\meshmap> py -3 manage.py loaddata contacts.json
Installed 6 object(s) from 1 fixture(s)
----

== Getting data out of a Django DB

* `py -3 manage.py dumpdata` will dump that data currently in the DB in JSON
  format
* Adding a `<app_name>` positional argument will dump all models in an app
* Adding a `<app_name>.<model>` positional argument will dump only that model

== Use cases and further reading

* Typically best for _initializing_ a database
* If you want a people to be able to upload CSV files and import them, design a
  view that does that, fixtures are for admins
* `dumpdata` is great for working on a project where you made a bunch of edits
  in the Admin interface and you want to reuse them
* https://docs.djangoproject.com/en/3.1/howto/initial-data/[Django docs: Providing initial data for models]
