= Migrations

== What are migrations?

[plantuml, migration, svg]
....
@startuml
database db1 as "Database v1" {
  rectangle table1 [
    <b>app_bakedgood
    ===
    id: integer
    ---
    name: varchar(32)
    ---
    price: decimal
  ]
}

actor dev as "Developer"
node python as "Python Script"
node sql as "SQL Script"

database db2 as "Database v2" {
  rectangle table2 [
    <b>app_bakedgood
    ===
    id: integer
    ---
    name: varchar(64)
    ---
    desc: varchar(256)
    ---
    price: decimal
    ---
    recipe: text
  ]
}

table1 --> dev
table1 --> python
table1 --> sql
dev --> table2
python --> table2
sql --> table2
@enduml
....

== Why use migrations?

[shrink]
* Maintaining a relational database while developing can be a pain
* What happens if you want to add a column?
* What happens if you want to change a name?
* You can write your own migrations in SQL, but it's prone to errors, tough to
  reverse and people often forget what they did.
* You also have the option to rebuild the DB each time (which may not be a bad
  idea).

[.columns]
== Activating Apps

[.column.is-one-third]
[.shrink]
* Django will _not_ make migrations for apps it doesn't know about
* You need to edit project settings

[.column]
--
.example_app/settings.py (excerpted)
[source, python]
----
...
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'example_app',
]
...
----
--

=== Warning!

WARNING: Not adding your app is a _very_ common mistake with non-obvious
results.

WARNING: Be sure you activated your virtual environment when making/applying
migrations!

== Make Migrations

[source, console]
----
(virtual_env) PS C:\Users\rxt1077\is601_example_project> py manage.py makemigrations
Migrations for 'example_app':
  example_app\migrations\0001_initial.py
    - Create model BakedGood
----

== SQL Migrate

[source, console]
----
(virtual_env) PS C:\Users\rxt1077\example> py manage.py sqlmigrate example_app 0001
BEGIN; <1>
--
-- Create model BakedGood
--
CREATE TABLE "app_bakedgood" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" varchar(64) NOT NULL,
    "desc" varchar(256) NOT NULL,
    "price" decimal NOT NULL,
    "recipe" text NOT NULL);
COMMIT;
----
<1> formatted for readability

== Applying Migrations

[source, console]
----
PS C:\Users\rxt1077\example> py -3 manage.py migrate
(virtual_env) PS C:\Users\rxt1077\is601_example_project> py manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, example_app, sessions <1>
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length...OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying example_app.0001_initial... OK
  Applying sessions.0001_initial... OK
----
<1> Notice there is a lot more here than just our app.

=== Common Usage

* Typically you will be running the `makemigrations` command followed by
`migrate`
* Migrating is done _interactively_ as you may need to provide input for
  something that would violate an DB integrity constraint.
