= Query Parameters

== Background

* URLs can contain query parameters:
  https://www.example.com/test?param1=val1&param2=val2
* They are typically used as part of a GET request
* They can pass small bits of information to the view, such as search parameters

== Accessing Query Parameters in Django

[.shrink]
Django stores the query parameters in a
https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.HttpRequest.GET[dictionary-like structure]
that is part of the _request_

.views.py
[source, python]
----
def index(request):
    param1 = request.GET['param1']
    param2 = request.GET['param2']
----

=== Double Check

[.shrink]
You may need to make sure the parameters are there and provide some default
values:

.meshmap/main/views.py
[source, python]
----
def parse_date(get_params, key, default):
    """
    Try to pull a date out of the query parameters, returning the default value
    on any errors.
    """
    if key in get_params:
        try:
            return datetime.fromisoformat(get_params[key])
        except ValueError:
            return default
    else:
        return default

def main(request):
    start = parse_date(request.GET, 'start',
        datetime.fromisoformat('1970-01-01T00:00:00+00:00'))
    end = parse_date(request.GET, 'end', timezone.now())
    contacts = Contact.objects.filter(time__gte=start).filter(time__lte=end)
----

== URL encoding

* URLs must be in a specific format (ASCII only, no spaces, not all characters)
* URLs use the `%` sign followed by two digits to represent special characters
* Original String: `spaces and special chars : ! + $`
* URL encoded: `spaces+and+special+chars+%3A+%21+%2B+%24`

[.columns]
== Pros and Cons of Query Parameters

.Pros
[.col]
* Easy to see what's happen (just look at the address bar)
* Can be simpler for optional parameters
* Simple to set up

.Cons
[.col]
* Ugly URLs
* More checking required in the view
* https://www.google.com/search?q=tomatillo[XSS Concerns] (did you really want to search for tomatillo?)
