# Generated by Django 3.1.5 on 2021-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('source_name', models.CharField(max_length=30)),
                ('source_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
