= Exercise 6

Since we have been discussing debugging, today we're going to analyze some code and see if we can figure out what's going wrong.
Here's our case study:

====
Alice is designing a postfix notation adding machine.
This machine uses parenthesis and the plus sign to designate two arguments to add together.
Arguments must either be integers or another addition operation.

For example:

[source,lisp]
----
(+ 1 1) <1>
(+ 1 2) <2>
(+ 2 (+ 3 3)) <3>
----
<1> this would yield 1
<2> this would yield 2
<3> this would yield 8

You can find Alice's code in the class git repo `exercise_6` directory.
You'll also find it here for reference:

[source,python]
----
include::../exercise_6/parser.py[]
----
====

Run Alice's program and answer the following questions:

. In what function are you getting an error?
. What function called the function that's giving you an error?
. How many functions calls in total were there before the error occurred?
. What is the type of error you're getting?
. Is the error a problem with the parser or it's input?
. If it's an input problem, how would you fix the input?
. If it's a parser problem, how would you fix the parser?
. How could you make the parser raise a ParserError if this happens again in the future?
. How many arguments does the addition operation in Alice's machine take?
