= Exercise 1

In this exercise, we will be:

. Installing Docker (if you don't have it already)
. Installing git (if you don't have it already)
. Cloning https://github.com/rxt1077/IS601[the class git repository.]
. Launching Django

== Installing Docker

Follow https://docs.docker.com/desktop/[these instructions] to install Docker
Desktop. If for some reason your personal machine is not capable of running
Docker Desktop, you can follow
https://docs.docker.com/toolbox/toolbox_install_windows/[these instructions] to
install Docker Toolbox.

WARNING: If you have Windows 10 Home, you may want to consider
https://docs.microsoft.com/en-us/education/windows/change-to-pro-education[
upgrading to Windows 10 Education], which is available from
https://ist.njit.edu/software-available-download/#w[IST].

WARNING: They make it particularly tough to find the Docker Toolbox EXE (Windows)
and PKG (MacOS) files. They are
https://github.com/docker/toolbox/releases/download/v19.03.1/DockerToolbox-19.03.1.exe[here]
and https://github.com/docker/toolbox/releases/download/v19.03.1/DockerToolbox-19.03.1.pkg[here],
respectively.

== Installing git

Windows::
* https://gitforwindows.org/[git for windows]: Installs git, git BASH, and a
  GUI. The git command can then be run from PowerShell, CMD, or the BASH shell
  (which it installs).
MacOS::
* https://sourceforge.net/projects/git-osx-installer/files/[git for Mac Installer]:
  Provides an easy installer for git on MacOS. 
* https://developer.apple.com/xcode/[Xcode]: Xcode installs a command line git
  and you may have it installed already.

== Cloning https://github.com/rxt1077/IS601[the class git repository.]

NOTE: Everything shown after the `>` prompt is the text you need to run in a
terminal. Lines that do not start with a `>` are the output of the commands.
Yours should match what is show. The prompt will also usually show you what
directory you are in.

NOTE: In MacOS, you can use the Terminal application, in Windows you can use
PowerShell as long as you are using Docker Desktop. If you are using Docker
Toolbox, you will want to use the Docker Quickstart Terminal.

[source, console]
----
PS C:\Users\rxt1077> git clone https://github.com/rxt1077/IS601 <1>
----
<1> Make sure you are in a directory that you have write permissions for. In
Windows you can `cd C:\Users\<Username>` (where <Username> is your user name),
in MacOS you should start in your home directory, but you can run `cd` just to
be sure. `cd` with no directory defaults to home in MacOS / Linux.
