= Exercise 4

NOTE: All file paths used in the exercises are relative to your base project
directory: `~/is601_example_project` this means that when something states that
you are changing `is601_example_project/urls.py` the full path is actually
`~/is601_example_project/is601_example_project/urls.py`.

In this exercise you will be:

. Creating a new app boringly named `example_app`
. Creating a function named `index` in `example_app/views.py`
. Creating the file `example_app/urls.py` to route URLs for your new app
. Editing the file `is601_example_project/urls.py` to include the URLs from `example_app/urls.py`
. Testing your view and creating a screen shot

== Activating Your Virtual Environment

Using the terminal, from within your `is601_example_project` directory that you
created in Exercise 1, run the following commands:

[source, console]
----
PS C:\Users\rxt1077\is601_example_project> ./virtual_env/Scripts/Activate.ps1 <1>
(virtual_env) PS C:\Users\rxt1077\is601_example_project> <2>
----
<1> on MacOS you will need to `source ./virtual_env/bin/activate`
<2> notice how the prompt changes, this means you've activated your virtual
    environment

== Creating a New App

Now we will use the `startapp` command to create a new app. `startapp` takes
an argument that tells it what to name the app. We will name ours
`example_app`.

[source, console]
----
(virtual_env) PS C:\Users\rxt1077\is601_example_project> py manage.py startapp example_app <1>
(virtual_env) PS C:\Users\rxt1077\is601_example_project> ls <2>


    Directory: C:\Users\rxt1077\is601_example_project


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          6/9/2021  11:35 AM                example_app <3>
d-----         5/26/2021   8:07 PM                is601_example_project
d-----         5/26/2021   7:57 PM                virtual_env
-a----         5/26/2021   8:09 PM              0 db.sqlite3
-a----         5/26/2021   8:06 PM            699 manage.py


(virtual_env) PS C:\Users\rxt1077\is601_example_project>
----
<1> Here is what each part of this command means:
* `py` - use the Python launcher to run Python. On MacOS this would be
  `python3`.
* `manage.py startapp app` - use the `startapp` command from `manage.py` to
  make a new app named `app`
<2> If the command succeeds, there is no output. We use `ls` to _list_ the files
so we can see if our `example_app` directory was created.
<3> The directory was created, so it worked!

WARNING: If you are using MacOS your output may look slightly different from
mine. You should still be able to see the outcome despite minor formating
differences and the effect will be the same.

== Creating a New View

=== Creating a View Function

Using your text editor, edit `example_app/views.py` to look like the following:

.example_app/views.py
[source, python]
----
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world!")
----

NOTE: You will need to know where your `is601_example_project` directory
(created in Exercise 1) is to load this file in your text editor. For most
Windows users it should be `C:\Users\<username>\is601_example_project` (where
<username> is your user name) for most Mac users it should be
`is601_example_project` in your home directory.

NOTE: View functions don't have to be named `index`. They can be named anything
that helps you keep track of what they are doing.

=== Routing URLs

Now that we have a function that returns the HTML we want to present to the
user, we need to specify which _routes_ will run that function. This is done
through the `urls.py` files.

Using your text editor, Create/edit these files to look like the code blocks.
Each code blocks _title_ tells you where in your `is601_example_project`
directory the file can be found. Note that for the second code block this is
the `is601_example_project` directory _within_ your `is601_example_project`
directory:

.example_app/urls.py
[source, python]
----
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]
----

NOTE: The above file _does not exist yet_. It will need to be created.

.is601_example_project/urls.py
[source, python]
----
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('example_app/', include('example_app.urls')),
    path('admin/', admin.site.urls),
]
----

NOTE: You can keep the comments at the top of `is601_example_project/urls.py` if you
like. They provide basic directions for how to add a URL

== Testing Your View

Lets bring the development server up so we can see if it works. Using the
terminal:

[source, console]
----
(virtual_env) PS C:\Users\rxt1077\is601_example_project> py manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin,
 auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
June 09, 2021 - 11:45:32
Django version 3.2.3, using settings 'is601_example_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
----

Assuming everything started, leave the development server running and visit
http://localhost:8000/example_app. You should see the text "Hello, world!". Take a
screen shot and submit that for your assignment. You can stop the development
server by typing Ctrl+C.
