= Exercise 1
:icons: font
:source-highlighter: rouge

In this exercise, we will be:

. Installing Python and/or pip
. Installing Django
. Creating/Running a Django site

== Installing Python and pip

Python is the programming language that Django uses. Pip is the Python package
management tool and we will be using it to install Django.

=== Windows

If you do not already have Python 3 installed, you can use this
https://www.python.org/ftp/python/3.8.7/python-3.8.7-amd64.exe[Windows
installer package]. Alternative packages can be found
https://www.python.org/downloads/release/python-387/[here].

=== MacOS

MacOS comes with Python 2, which is depreciated. If you do not already have
Python 3 installed, you can use this
https://www.python.org/ftp/python/3.8.7/python-3.8.7-macosx10.9.pkg[MacOS
installer package]. Alternative packages can be found 
https://www.python.org/downloads/release/python-387/[here].

Follow the installer directions to install Python 3 for your operating system.

== Installing Django

Now we are ready to install Django via pip. Run `py -m pip install django` from
a terminal.

NOTE: In Windows, pay attention to the output. You will need to know the path
that `django-admin.py` is installed in. It should come up as a warning in
yellow. This shouldn't be an issue in MacOS.

== Creating/Running a Django Project

The `django-admin.py` script is used to create a project. You can see where it
is installed in the previous step. Here is an example console session where I
create and run a Django project named `example` in PowerShell:

[source, text]
----
PS C:\Users\rxt1077> py C:\Users\rxt1077\AppData\Local\Programs\Python\Python38\Scripts\django-admin.py startproject example
PS C:\Users\rxt1077> cd example
PS C:\Users\rxt1077\example> py -3 manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
January 20, 2021 - 15:28:16
Django version 3.1.5, using settings 'example.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
----

Now visit http://localhost:8000 in a web browser and you should see a message
stating, "The install worked successfully! Congratulations!" Take a screen shot
and submit that as your work for this exercise.

To shut everything down type `Ctrl+C` (hold Control and press C at the same
time) in your terminal window.
