= Exercise 6

The is the first exercise where you will be using what we have learned to
create something of your own design. It is far less prescriptive than the
previous exercises.

== Goal

Design a new view for the `example` app that uses a template and displays
information that is passed via the context.

NOTE: Feel free to `git clone` the class repository to a new directory if you want
a fresh start with the most current `example` app. You could also stash or
fetch and merge depending on your knowledge of git, just be sure to preserver
your project work if you are working in the same directory.

== What needs to be changed

`example/views.py`:: will need a new view function that uses `render` and passes
context.
`example/urls.py`:: will need a new route that points to your view function
`example/templates/example/<template_name>.html`:: you will need to create a
template in the `example` app (name it whatever you like,
replace <template_name>).

== Deliverables

Take a screenshot of your web browser showing your new view. Make sure to
capture the URL information in the address bar at the top.
