= Exercise 6

The is the first exercise where you will be using what we have learned to
create something of your own design. It is far less prescriptive than the
previous exercises.

== Goal

Design a new view for the `example_app` app that uses a template and displays
information that is passed via the context.

== What needs to be changed

`example_app/views.py`:: will need a new view function that uses `render` and passes
context.
`example_app/urls.py`:: will need a new route that points to your view function
`example_app/templates/example_app/<template_name>.html`:: you will need to create a template
in the `example_app` app (name it whatever you like, replace <template_name>).

NOTE: The information you pass in the context does not have to be important. At
this point the goal is to learn _how_ to pass variables into your templates.

== Deliverables

Take a screenshot of your web browser showing your new view. Make sure to
capture the URL information in the address bar at the top.
