# Generated by Django 3.0.6 on 2020-06-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BakedGoods',
            new_name='BakedGood',
        ),
    ]
