# Generated by Django 3.0.6 on 2020-06-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_bakedgood_good_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='bakedgood',
            name='ingredients',
            field=models.ManyToManyField(to='example.Ingredient'),
        ),
    ]
